[package]
name = "wick-component"
version = "0.15.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Macros and exports used to create Wick components"
keywords = ["wasm", "wick", "wasmflow", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
homepage = "https://candle.dev"
readme = "README.md"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["json"]
datetime = ["chrono/serde", "wick-packet/datetime"]
uuid = ["flow-component/uuid"]
json = []

[dependencies]
wick-packet = { workspace = true, default-features = false }
wick-operation = { workspace = true }
flow-component = { workspace = true, default-features = false }
wasmrs = { workspace = true }
wasmrs-rx = { workspace = true }
wasmrs-codec = { workspace = true, features = ["std"] }
wasmrs-runtime = { workspace = true }
tokio-stream = { workspace = true }
paste = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true, features = ["std"], optional = true }
bytes = { workspace = true, optional = true }
async-recursion = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasmrs-guest = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde = { workspace = true }
anyhow = { workspace = true }
wick-logger = { workspace = true }
test-logger = { workspace = true }
tracing = { workspace = true }
serde-value = { workspace = true }
