[package]
name = "wick-component"
version = "0.15.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Macros and exports used to create Wick components"
keywords = ["wasm", "wick", "wasmflow", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
homepage = "https://candle.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]

[dependencies]
wick-packet = { workspace = true, default-features = false }
wasmrs = { workspace = true }
wasmrs-rx = { workspace = true }
wasmrs-runtime = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
paste = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
