[package]
name = "wick-wascap"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "WASM Capabilities library for Wick"
include = [
  "src/**/*",
  "README.md",
  "test/test_wasi_component.wasm",
  "!**/test/**/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { workspace = true, features = ["derive"] }
wick-interface-types = { workspace = true, features = ["value"] }
thiserror = { workspace = true }
wasmparser = { workspace = true }
wasm-encoder = { workspace = true }
data-encoding = { workspace = true }
ring = { workspace = true }
nuid = { workspace = true }
tracing = { workspace = true }
base64 = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
nkeys = { workspace = true }
humantime = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
rstest = { workspace = true }
