[package]
name = "wick-wascap"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "WASM Capabilities library for Wick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { workspace = true, features = ["derive"] }
wick-interface-types = { workspace = true, features = ["value"] }
thiserror = { workspace = true }
wascap = { workspace = true }
wasmparser = { workspace = true }
wasm-encoder = { workspace = true }
wasm-gen = { workspace = true }
data-encoding = { workspace = true }
ring = { workspace = true }
nuid = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
rstest = { workspace = true }
