[package]
name = "wick-wascap"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wascap = "0.8"
serde = { workspace = true, features = ["derive"] }
wick-interface-types = { path = "../wick-interface-types" }
thiserror = { workspace = true }
walrus = "0.19"
data-encoding = "2.3.2"
ring = "0.16"
nuid = "0.4"
tracing = { workspace = true }

[dev-dependencies]
anyhow = { version = "1.0" }
