[package]
name = "wasmflow-streams"
version = "0.10.0-beta.4"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/wasmflow/wasmflow-sdk"
description = "Rust library encapsulating the message packets sent across Wasmflow components."
documentation = "https://wasmflow.com"
keywords = ["wasmflow", "actor", "flow"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
homepage = "https://wasmflow.com"


[features]

[dependencies]
wasmflow-packet = { path = "../wasmflow-packet", version = "0.10.0-beta.4" }
futures = "0.3.21"
pin-project-lite = "0.2.9"

[dev-dependencies]
env_logger = "0.9"
test-log = "0.2.8"
anyhow = "1.0"
tracing = "0.1"
