[package]
name = "derive-asset-container"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
description = "Derive AssetManager trait"
repository = "https://github.com/candlecorp/wick"
include = ["src/lib.rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["parsing", "extra-traits"] }
asset-container = { workspace = true }
structmeta = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "fs",
  "rt-multi-thread",
  "io-util"
] }
tokio-util = { workspace = true, features = ["io", "codec"] }
tokio-stream = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
