[package]
name = "wick-packet"
version = "0.15.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Packet, stream, and entity types for Wick, a WebAssembly application flow runtime"
documentation = "https://candle.dev"
keywords = ["wasm", "wick", "wasmflow", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
homepage = "https://candle.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
invocation = ["uuid", "rng"]
rt-tokio = ["tokio/rt"]
datetime = ["chrono"]
validation = []
rng = ["seeded-random/rng"]
std = ["seeded-random/std"]
test = ["invocation", "std"]

[dependencies]
wick-interface-types = { workspace = true, features = ["typeid"] }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
wasmrs = { workspace = true }
wasmrs-frames = { workspace = true, features = ["derive_serde"] }
wasmrs-rx = { workspace = true }
wasmrs-codec = { workspace = true }
liquid-json = { workspace = true, features = ["serde"] }
bytes = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true }
url = { workspace = true }
pin-project-lite = { workspace = true }
base64-serde = { workspace = true }
base64 = { workspace = true, default-features = false, features = ["alloc"] }
tokio-stream = { workspace = true, default-features = false }
#
# feature = rt-tokio
tokio = { workspace = true, optional = true, features = ["rt"] }
#
# feature = invocation
seeded-random = { workspace = true, optional = true }
uuid = { workspace = true, features = ["v4", "serde"], optional = true }
#
# feature = datetime
chrono = { workspace = true, optional = true, features = [
  "serde"
], default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
wasmrs-guest = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
rstest = { workspace = true }
