[package]
name = "wick-packet"
version = "0.14.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Packet, stream, and entity types for Wick, a WebAssembly application flow runtime"
documentation = "https://candle.dev"
keywords = ["wasm", "wick", "wasmflow", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
homepage = "https://candle.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
invocation = ["uuid", "seeded-random"]

[dependencies]
wick-interface-types = { workspace = true, features = ["typeid"] }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"], optional = true }
thiserror = { workspace = true }
wasmrs = { workspace = true }
wasmrs-frames = { workspace = true, features = ["derive_serde"] }
wasmrs-rx = { workspace = true }
wasmrs-codec = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true }
url = { workspace = true }
# TODO make these feature flags
wasmrs-guest = { workspace = true }
wasmrs-runtime = { workspace = true }
seeded-random = { workspace = true, optional = true }
pin-project-lite = "0.2"

[dev-dependencies]
anyhow = { workspace = true }
