[package]
name = "flow-expression-parser"
version = "0.5.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Parser for flow expressions in the Wick configuration manifest."


[dependencies]
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
nom = { workspace = true, features = ["alloc"] }
liquid-json = { workspace = true, features = ["serde"] }
once_cell = { workspace = true }
seeded-random = { workspace = true, features = ["std", "rng", "uuid"] }
parking_lot = { workspace = true }


[dev-dependencies]
tracing = { workspace = true }
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
wick-logger = { workspace = true }
test-logger = { workspace = true }
rstest = { workspace = true }
