[package]
name = "flow-expression-parser"
version = "0.5.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Parser for flow expressions in the Wick configuration manifest."

[dependencies]
lazy_static = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
nom = { workspace = true, features = ["alloc"] }

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
wick-logger = { workspace = true }
test-logger = { workspace = true }
tracing = { workspace = true }
rstest = { workspace = true }
