[package]
name = "wasmflow-host"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
seeded-random = { path = "../../misc/seeded-random" }
wasmflow-runtime = { path = "../wasmflow-runtime" }
wasmflow-mesh = { path = "../wasmflow-mesh" }
wasmflow-manifest = { path = "../wasmflow-manifest" }
wasmflow-loader = { path = "../wasmflow-loader" }
wasmflow-collection-cli = { path = "../wasmflow-collection-cli" }
wasmflow-rpc = { path = "../wasmflow-rpc" }
wasmflow-invocation-server = { path = "../wasmflow-invocation-server" }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
http = "0.2"
once_cell = { workspace = true }
parking_lot = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "time",
  "io-std",
  "io-util",
  "macros",
] }
anyhow = { workspace = true }
tokio-stream = { workspace = true }
