[package]
name = "flow-graph"
version = "0.21.1"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "A representation of a graph data structure for flow-based programming."
include = ["src/**/*", "LICENSE"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
