[package]
name = "flow-graph"
version = "0.20.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
wick-config = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
logger = { workspace = true }
test-logger = { workspace = true }
anyhow = { workspace = true }
