[package]
name = "test-bdd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "A BDD runner specific to Wick tests"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cucumber = { version = "0.19", features = ["macros"] }
futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true }
tracing = { workspace = true }
