[package]
name = "test-bdd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "A BDD runner specific to Wick tests"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cucumber = { version = "0.19", features = ["macros"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
tracing = "0.1"
