[package]
name = "wasmflow-interface-keyvalue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["host"]
host = []
guest = []

[dependencies]
wasmflow-sdk = { path = "../../wasmflow/wasmflow-sdk", features = ["v1"] }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
