[package]
name = "wasmflow-runtime"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
publish = false

[features]

[dependencies]
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
wasmflow-schematic-graph = { path = "../wasmflow-schematic-graph" }
wasmflow-interpreter = { path = "../wasmflow-interpreter" }
wasmflow-manifest = { path = "../wasmflow-manifest" }
wasmflow-loader = { path = "../wasmflow-loader" }
wasmflow-collection-wasm = { path = "../wasmflow-collection-wasm" }
wasmflow-collection-nats = { path = "../wasmflow-collection-nats" }
wasmflow-collection-grpctar = { path = "../wasmflow-collection-grpctar" }
wasmflow-collection-grpc = { path = "../wasmflow-collection-grpc" }
wasmflow-mesh = { path = "../wasmflow-mesh" }
wasmflow-stdlib = { path = "../wasmflow-stdlib" }
wasmflow-rpc = { path = "../wasmflow-rpc" }

seeded-random = { path = "../../misc/seeded-random" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.10"
serde-value = "0.7.0"

futures = "0.3"
async-trait = "0.1.50"
once_cell = "1.8"
parking_lot = { version = "0.12", features = [] }
thiserror = "1.0"
tokio = { version = "1", features = [
  "macros",
  "time",
  "sync",
  "rt-multi-thread",
] }
tokio-stream = { version = "0.1", features = [] }
tracing = "0.1"
uuid = "1.1"
anyhow = "1.0.62"
atty = "0.2.14"

[dev-dependencies]
wasmflow-invocation-server = { path = "../wasmflow-invocation-server" }
test-native-collection = { path = "../../integration/test-native-collection" }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
maplit = "1.0"
pretty_assertions = "1"
lazy_static = "1.4"
anyhow = "1.0"
runtime-testutils = { path = "./tests/runtime_utils" }
