[package]
name = "wasmflow-runtime"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
publish = false

[features]

[dependencies]
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
wasmflow-schematic-graph = { path = "../wasmflow-schematic-graph" }
wasmflow-interpreter = { path = "../wasmflow-interpreter" }
wasmflow-manifest = { path = "../wasmflow-manifest" }
wasmflow-loader = { path = "../wasmflow-loader" }
wasmflow-collection-wasm = { path = "../wasmflow-collection-wasm" }
wasmflow-collection-nats = { path = "../wasmflow-collection-nats" }
wasmflow-collection-grpctar = { path = "../wasmflow-collection-grpctar" }
wasmflow-collection-grpc = { path = "../wasmflow-collection-grpc" }
wasmflow-mesh = { path = "../wasmflow-mesh" }
wasmflow-stdlib = { path = "../wasmflow-stdlib" }
wasmflow-rpc = { path = "../wasmflow-rpc" }
seeded-random = { path = "../../misc/seeded-random" }
tokio = { workspace = true, features = [
  "macros",
  "time",
  "sync",
  "rt-multi-thread",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
serde-value = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
atty = "0.2"

[dev-dependencies]
wasmflow-invocation-server = { path = "../wasmflow-invocation-server" }
test-native-collection = { path = "../../integration/test-native-collection" }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
maplit = "1.0"
pretty_assertions = "1"
lazy_static = "1.4"
anyhow = { workspace = true }
runtime-testutils = { path = "./tests/runtime_utils" }
