project_name: nanobus
builds:
  - id: nanobus
    main: ./cmd/nanobus
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly
archives:
  - id: nanobus
    builds:
      - nanobus
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
        - README.md
        - LICENSE.txt
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# brews:
#   - name: NanoBus
#     tap:
#       owner: nanobus
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://nanobus.io
#     description: NanoBus is a lightweight microservice runtime that reduces developer responsibility so that teams can focus on core application logic.
#     license: "ELv2"

release:
  github:
    owner: nanobus
    name: nanobus
  prerelease: auto
  draft: false
