[workspace]
members = [
  "crates/interfaces/*",
  "crates/integration/test-native-component",
  "crates/misc/*",
  # "crates/collections/*",
  "crates/bins/*",
  "crates/wick/*",
]
exclude = [
  "crates/integration/test-baseline-component",
  "crates/integration/test-cli-trigger-component",
  "crates/integration/test-http-trigger-component",
  "crates/wick/wick-component-grpc", #TODO: remove/fix

]

[workspace.dependencies]
wick-interface-http = { path = "./crates/interfaces/wick-interface-http", version = "0.1.0" }
wick-packet = { path = "./crates/wick/wick-packet", version = "0.14.0" }
wick-stdlib = { path = "./crates/wick/wick-stdlib", version = "0.1.0" }
wick-xdg = { path = "./crates/wick/wick-xdg", version = "0.1.0" }
wick-interface-types = { path = "./crates/wick/wick-interface-types", version = "0.14.0" }
wick-invocation-server = { path = "./crates/wick/wick-invocation-server", version = "0.1.0" }
wick-rpc = { path = "./crates/wick/wick-rpc", version = "0.1.0" }
wick-component = { path = "./crates/wick/wick-component", version = "0.14.0" }
wick-component-codegen = { path = "./crates/wick/wick-component-codegen", version = "0.3.0" }
wick-component-wasm = { path = "./crates/wick/wick-component-wasm", version = "0.1.0" }
wick-component-cli = { path = "./crates/wick/wick-component-cli", version = "0.1.0" }
wick-runtime = { path = "./crates/wick/wick-runtime", version = "0.20.0" }
wick-host = { path = "./crates/wick/wick-host", version = "0.1.0" }
wick-config = { path = "./crates/wick/wick-config", version = "0.24.0" }
wick-test = { path = "./crates/wick/wick-test", version = "0.0.0" }
wick-wascap = { path = "./crates/wick/wick-wascap", version = "0.1.0" }
wick-oci-utils = { path = "./crates/wick/wick-oci-utils", version = "0.1.0" }
wick-package = { path = "./crates/wick/wick-package", version = "0.1.0" }
wick-grpctar = { path = "./crates/wick/wick-grpctar", version = "0.1.0" }
wick-asset-reference = { path = "./crates/wick/wick-asset-reference", version = "0.1.0" }
flow-expression-parser = { path = "./crates/wick/flow-expression-parser", version = "0.4.0" }
flow-graph-interpreter = { path = "./crates/wick/flow-graph-interpreter", version = "0.20.0" }
flow-graph = { path = "./crates/wick/flow-graph", version = "0.20.0" }
logger = { path = "./crates/wick/logger", version = "0.1.0" }
seeded-random = { path = "./crates/misc/seeded-random", version = "0.3.0" }
tap = { path = "./crates/misc/tap", version = "0.0.0" }
rot = { path = "./crates/misc/rot", version = "0.1.0" }
assets = { path = "./crates/misc/assets", version = "0.1.0" }
derive-assets = { path = "./crates/misc/derive-assets", version = "0.1.0" }
performance-mark = { path = "./crates/misc/performance-mark", version = "0.0.1" }
test-logger = { path = "./crates/misc/test-logger", version = "0.1.0" }
tokio-test-bin = { path = "./crates/misc/tokio-test-bin", version = "0.3.0" }
test-native-component = { path = "./crates/integration/test-native-component", version = "0.1.0" }
xdg = "2.4"
console = "0.15"
quote = "1.0"
syn = "2.0"
proc-macro2 = "1.0"
heck = "0.4"
tar = "0.4"
serde-with-expand-env = "1.1"
http = "0.2"
cfg-if = "1.0"
async-stream = "0.3"
env_logger = "0.10"
num-traits = "0.2"
bytes = "1.4"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
serde-value = "0.7"
tokio = "1"
tokio-stream = "0.1"
tokio-util = "0.7"
futures = "0.3"
tracing = "0.1"
tracing-futures = "0.2"
async-trait = "0.1"
thiserror = "1.0"
parking_lot = "0.12"
once_cell = "1.8"
uuid = "1.1"
anyhow = "1.0"
async-recursion = "1.0"
clap = "4.1"
tonic = "0.8"
tonic-build = "0.8"
tonic-reflection = "0.6"
reqwest = "0.11"
rand = "0.8"
shellexpand = "3.0"
regex = "1"
k9 = "0.11"
lazy_static = "1.4"
test-log = "0.2"
nom = "7.1"
serde_repr = "0.1"
pretty_assertions = "1.3"
# wasmrs = { path = "../wasmrs-rust/crates/wasmrs" }
# wasmrs-rx = { path = "../wasmrs-rust/crates/wasmrs-rx" }
# wasmrs-frames = { path = "../wasmrs-rust/crates/wasmrs-frames" }
# wasmrs-codec = { path = "../wasmrs-rust/crates/wasmrs-codec" }
# wasmrs-wasmtime = { path = "../wasmrs-rust/crates/wasmrs-wasmtime" }
# wasmrs-host = { path = "../wasmrs-rust/crates/wasmrs-host" }
# wasmrs-runtime = { path = "../wasmrs-rust/crates/wasmrs-runtime" }
# wasmrs-guest = { path = "../wasmrs-rust/crates/wasmrs-guest" }
wasmrs = { version = "0.8" }
wasmrs-rx = { version = "0.8" }
wasmrs-frames = { version = "0.8" }
wasmrs-codec = { version = "0.8" }
wasmrs-wasmtime = { version = "0.8" }
wasmrs-host = { version = "0.8" }
wasmrs-runtime = { version = "0.8" }
wasmrs-guest = { version = "0.8" }
rand_chacha = "0.3"
oci-distribution = "0.9"
url = "2.3"
dyn-clone = "1.0"
prost = "0.11"
prost-types = "0.11"
atty = "0.2"
wascap = "0.8"
walrus = "0.19"
data-encoding = "2.3.2"
ring = "0.16"
nuid = "0.4"
paste = "1.0"
hyper = "0.14"
sha256 = "1.1"
tracing-opentelemetry = "0.18.0"
opentelemetry = { version = "0.18.0" }
opentelemetry-jaeger = { version = "0.17.0" }
tracing-log = "0.1"
tracing-subscriber = "0.3"
normpath = "1.1"
