[package]
name = "wasmflow-root"
version = "0.0.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
description = "Application data flow platform"
repository = "https://github.com/wasmflow/wasmflow"
documentation = "https://wasmflow.com"
readme = "README.md"

[profile.release]
opt-level = 3
debug = 0
incremental = true
codegen-units = 4

[features]

[dependencies]

[dev-dependencies]
wasmflow-sdk = { path = "./crates/wasmflow/wasmflow-sdk", features = ["v1"] }
logger = { path = "./crates/wasmflow/logger" }
test-native-collection = { path = "./crates/integration/test-native-collection" }
wasmflow-rpc = { path = "./crates/wasmflow/wasmflow-rpc" }
utils = { path = "./tests/utils" }
maplit = "1.0"
tokio = { workspace = true, features = [
  "macros",
  "process",
  "time",
  "net",
  "rt-multi-thread",
] }
futures = { workspace = true }
log = "0.4"
test-logger = { path = "./crates/misc/test-logger" }
anyhow = { workspace = true }
serde_json = { workspace = true }

[workspace]
members = [
  "crates/interfaces/*",
  "crates/integration/*",
  "crates/misc/*",
  "crates/collections/*",
  "crates/bins/*",
  "crates/wasmflow/*",
]
exclude = [
  "crates/integration/test-wasm-component",
  "crates/integration/test-wasi-component",
  "crates/integration/test-main-component",
  "crates/integration/test-main-network-component",
  "crates/wasmflow/wasmflow-sdk",
]

[workspace.dependencies]
env_logger = "0.10.0"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
serde-value = "0.7"
tokio = "1"
tokio-stream = "0.1"
futures = "0.3"
tracing = "0.1"
tracing-futures = "0.2"
async-trait = "0.1"
thiserror = "1.0"
parking_lot = "0.12"
once_cell = "1.8"
uuid = "1.1"
anyhow = "1.0"
async-recursion = "1.0"
clap = "4.1"
tonic = "0.8"
tonic-build = "0.8"
rand = "0.8"
shellexpand = "3.0"
regex = "1"
