[workspace]
members = [
  # "crates/interfaces/*",
  "crates/integration/test-native-collection",
  "crates/misc/*",
  # "crates/collections/*",
  "crates/bins/*",
  "crates/wick/*",
]
exclude = [
  "crates/integration/test-baseline-component",
  "crates/integration/test-wasm-component",
  "crates/integration/test-wasi-component",
  "crates/integration/test-main-component",
  "crates/integration/test-main-network-component",
  "crates/wick/wick-component-grpc", #TODO: remove/fix

]

[workspace.dependencies]
env_logger = "0.10.0"
bytes = "1.4"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
serde-value = "0.7"
tokio = "1"
tokio-stream = "0.1"
futures = "0.3"
tracing = "0.1"
tracing-futures = "0.2"
async-trait = "0.1"
thiserror = "1.0"
parking_lot = "0.12"
once_cell = "1.8"
uuid = "1.1"
anyhow = "1.0"
async-recursion = "1.0"
clap = "4.1"
tonic = "0.8"
tonic-build = "0.8"
rand = "0.8"
shellexpand = "3.0"
regex = "1"
k9 = "0.11"
wasmrs = { path = "../wasmrs-rust/crates/wasmrs" }
wasmrs-rx = { path = "../wasmrs-rust/crates/wasmrs-rx" }
wasmrs-frames = { path = "../wasmrs-rust/crates/wasmrs-frames" }
wasmrs-codec = { path = "../wasmrs-rust/crates/wasmrs-codec" }
wasmrs-wasmtime = { path = "../wasmrs-rust/crates/wasmrs-wasmtime" }
wasmrs-host = { path = "../wasmrs-rust/crates/wasmrs-host" }
wasmrs-runtime = { path = "../wasmrs-rust/crates/wasmrs-runtime" }
