[package]
name = "wasmflow-root"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
description = "Application data flow platform"
repository = "https://github.com/wasmflow/wasmflow-core"
documentation = "https://wasmflow.com"
readme = "README.md"

[profile.release]
opt-level = 3
debug = 0
incremental = true

[features]

[dependencies]

[dev-dependencies]
wasmflow-invocation = { path = "./crates/sdk/wasmflow-invocation" }
wasmflow-entity = { path = "./crates/sdk/wasmflow-entity" }
wasmflow-codec = { path = "./crates/sdk/wasmflow-codec" }
wasmflow-packet = { path = "./crates/sdk/wasmflow-packet" }
wasmflow-output = { path = "./crates/sdk/wasmflow-output", features = [] }
wasmflow-transport = { path = "./crates/sdk/wasmflow-transport", features = [
  "all",
] }
logger = { path = "./crates/wasmflow/logger" }
test-native-collection = { path = "./crates/integration/test-native-collection" }
wasmflow-rpc = { path = "./crates/wasmflow/wasmflow-rpc" }
wasmflow-macros = { path = "./crates/sdk/wasmflow-macros" }
utils = { path = "./tests/utils" }
maplit = "1.0"
tokio = { version = "1.4", features = [
  "macros",
  "process",
  "time",
  "net",
  "rt-multi-thread",
] }
futures = "0.3"
log = "0.4"
test-logger = { path = "./crates/misc/test-logger" }
anyhow = "1.0"
serde_json = "1.0"

# bench specific
criterion = { version = "0.3", features = ["async", "async_tokio"] }
once_cell = "1.8"
wasmflow-host = { path = "./crates/wasmflow/wasmflow-host" }
seeded-random = { path = "./crates/misc/seeded-random" }

[workspace]
members = [
  "crates/interfaces/*",
  "crates/integration/*",
  "crates/misc/*",
  "crates/collections/*",
  "crates/bins/*",
  "crates/wasmflow/*",
]

exclude = [
  "crates/integration/test-wasm-component",
  "crates/integration/test-wasi-component",
  "crates/integration/test-main-component",
  "crates/integration/test-main-network-component",
  "sdk/",
  "forks/wapc-rs/",
]

[[bench]]
name = "create-user"
harness = false

[[bench]]
name = "markdown"
harness = false
