[target.aarch64-unknown-linux-gnu]
image = "candlecorp/cross:aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image = "candlecorp/cross:x86_64-unknown-linux-gnu"

[target.aarch64-apple-darwin]
image = "candlecorp/cross:aarch64-apple-darwin"

[target.x86_64-apple-darwin]
image = "candlecorp/cross:x86_64-apple-darwin"

[target.x86_64-pc-windows-gnu]
image = "candlecorp/cross:x86_64-pc-windows-gnu"

[build.env]
passthrough = [
  "WICK_VERSION",
  "SCCACHE_AZURE_BLOB_CONTAINER",
  "CARGO_PROFILE_RELEASE_DEBUG",
  "CARGO_INCREMENTAL",
  "CARGO_PROFILE_RELEASE_LTO",
  "CARGO_PROFILE_RELEASE_OPT_LEVEL",
  "CARGO_PROFILE_RELEASE_CODEGEN_UNITS",
  "CARGO_PROFILE_RELEASE_STRIP",
]
