[toolchain]
channel = "1.71.0"
components = ["rustfmt", "clippy"]
targets = [
  "wasm32-unknown-unknown",
  "wasm32-wasi",
  "aarch64-unknown-linux-gnu",
  "x86_64-pc-windows-gnu",
  "aarch64-apple-darwin",
]
