[package]
name = "wasmflow-collection-cli"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ['cli']
reflection = ["tonic-reflection"]
cli = ['grpc', 'mesh']
grpc = [
  'wasmflow-rpc',
  'tonic/tls',
  'wasmflow-invocation-server',
  'async-stream',
]
mesh = ['wasmflow-rpc', 'wasmflow-mesh', 'async-stream']

[dependencies]
logger = { path = "../logger" }

wasmflow-rpc = { path = "../wasmflow-rpc", optional = true }
wasmflow-invocation-server = { path = "../wasmflow-invocation-server", optional = true }
wasmflow-mesh = { path = "../wasmflow-mesh", optional = true }

wasmflow-packet = { path = "../../sdk/wasmflow-packet" }
wasmflow-codec = { path = "../../sdk/wasmflow-codec" }
wasmflow-transport = { path = "../../sdk/wasmflow-transport", features = [
  "all",
] }

cfg-if = "1.0"

tonic = { version = "0.7", optional = true }
tonic-reflection = { version = "0.4", default-features = false, optional = true }

tokio = { version = "1", features = [
  "macros",
  "fs",
  "net",
  "signal",
  "rt-multi-thread",
] }
tokio-stream = "0.1.6"
async-stream = { version = "0.3.2", optional = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tracing = "0.1"
thiserror = "1.0"
clap = { version = "3.0", features = ["derive", "env"] }
uuid = { version = "1.1", features = ["v4"] }

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
test-native-collection = { path = "../../integration/test-native-collection" }
once_cell = "1.8"
reqwest = { version = "0.11", features = ["json"] }
anyhow = "1.0"
serde_json = "1.0"
