[package]
name = "wasmflow-collection-cli"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ['cli']
reflection = ["tonic-reflection"]
cli = ['grpc', 'mesh']
grpc = [
  'wasmflow-rpc',
  'tonic/tls',
  'wasmflow-invocation-server',
  'async-stream',
]
mesh = ['wasmflow-rpc', 'async-stream']

[dependencies]
logger = { path = "../logger" }
wasmflow-rpc = { path = "../wasmflow-rpc", optional = true }
wasmflow-packet-stream = { path = "../wasmflow-packet-stream" }
wasmflow-invocation-server = { path = "../wasmflow-invocation-server", optional = true }
# wasmflow-mesh = { path = "../wasmflow-mesh", optional = true }
cfg-if = "1.0"
tonic = { workspace = true, optional = true }
tonic-reflection = { version = "0.6", default-features = false, optional = true }
tokio = { workspace = true, features = [
  "macros",
  "fs",
  "net",
  "signal",
  "rt-multi-thread",
] }
tokio-stream = { workspace = true }
async-stream = { version = "0.3.2", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
test-native-collection = { path = "../../integration/test-native-collection" }
once_cell = { workspace = true }
reqwest = { version = "0.11", features = ["json"] }
anyhow = { workspace = true }
serde_json = { workspace = true }
