[package]
name = "wasmflow-stdlib"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
publish = false

[features]
default = ["host"]
host = []
guest = []

[dependencies]
wasmflow-packet-stream = { path = "../wasmflow-packet-stream" }
wasmflow-rpc = { path = "../wasmflow-rpc" }
wasmflow-interface = { path = "../wasmflow-interface", features = ["parser"] }
# wasmflow-interface = { path = "../wasmflow-interface" }
seeded-random = { path = "../../misc/seeded-random" }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
thiserror = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
wasmflow-stdlib = { path = ".", features = ["guest"] }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
futures = { workspace = true }
anyhow = { version = "1.0" }
