name: mycli
version: 1.0.0
channels:
  cli:
    uses: channels.wasmflow.cli@v1
    with:
      location: build/test_cli_channel_component.signed.wasm
      component: main
      link:
        kind: Manifest
        reference: ./noop.wafl
