[package]
name = "wick-grpctar"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
serde_json = "1"
serde_yaml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tar = "0.4.38"
wick-interface-types = { path = "../wick-interface-types" }
wick-wascap = { path = "../wick-wascap" }

[dev-dependencies]
anyhow = { workspace = true }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
clap = { workspace = true, features = ["derive", "env"] }
async-recursion = { workspace = true }
env_logger = { workspace = true }
