---
version: 0
network:
  schematics:
    - name: native_component
      instances:
        add:
          id: vino::math::add
        add2:
          id: vino::math::add
      connections:
        - <> => add[left]
        - <> => add[right]
        - <> => add2[right]
        - add[output] => add2[left]
        - add2[output] => <>
