[package]
name = "wasmflow-interface"
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
description = "Types used by the Wasmflow tool chain"
documentation = "https://wasmflow.com"
keywords = ["types", "wasmflow"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[dependencies]
serde = { workspace = true, features = ["derive"] }
wasmflow-macros = { path = "../wasmflow-macros", version = "0.10.0-beta.4" }
serde_repr = "0.1"

[dev-dependencies]
anyhow = { workspace = true }
test-log = "0.2.8"
env_logger = { workspace = true }
pretty_assertions = "1.2"
serde_json = { workspace = true }
