[package]
name = "wasmflow-interface"
version = "0.10.0-beta.1"
edition = "2021"
license = "BSD-3-Clause"
description = "Types used by the Wasmflow tool chain"
documentation = "https://wasmflow.com"
keywords = ["types", "wasmflow"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasmflow-macros = { path = "../wasmflow-macros", version = "0.10.0-beta.1" }
serde_repr = "0.1"

[dev-dependencies]
anyhow = "1.0"
test-log = "0.2.8"
env_logger = "0.9"
pretty_assertions = "1.2"
serde_json = "1.0"
