[package]
name = "wick-sql"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "SQL Database component for the wick project."

[features]

[dependencies]
wick-packet = { workspace = true, features = ["rt-tokio", "datetime"] }
flow-component = { workspace = true, features = ["invocation"] }
wick-config = { workspace = true }
wick-rpc = { workspace = true }
wick-interface-types = { workspace = true, features = ["parser"] }
url = { workspace = true }
# sqlx
sqlx = { workspace = true, features = [
  "runtime-tokio-rustls",
  "postgres",
  "sqlite",
  "json",
  "any",
  "chrono",
] }
# tiberius & pool
tiberius = { workspace = true, features = [
  "rustls",
  "tds73",
  "chrono",
], default-features = false }
bb8-tiberius = { workspace = true, features = ["with-tokio"] }
bb8 = { workspace = true }
#
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
#
futures = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }
#
bytes = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
once_cell = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wick-logger = { workspace = true }
test-logger = { workspace = true }
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
wick-packet = { workspace = true, features = ["test"] }
