---
apiVersion: wick.candle.dev/v1alpha1
kind: Type
imports:
  - StatusCode
  - HttpVersion
HttpResponse:
  #HTTP version enum
  version: HttpVersion
  #status code enum
  status: StatusCode=OK
  #All response headers. Duplicates are not supported.
  headers: { string:string }
  #All response headers, as a single string in case duplicate headers exist.
  headersRaw: string
  #Response body in bytes. optional.
  body: bytes?
