[package]
name = "wasmflow-macros"
version = "0.10.0-beta.2"
edition = "2021"
license = "BSD-3-Clause"
description = "Macros use by wasmflow libraries"
documentation = "https://wasmflow.com"
keywords = ["macros", "wasmflow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]

[dev-dependencies]
anyhow = "1.0"
