[package]
name = "wasmflow"
version = "0.4.1"
edition = "2021"
default-run = "wasmflow"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wasmflow-sdk = { path = "../../wasmflow/wasmflow-sdk", features = ["v1"] }
wasmflow-rpc = { path = "../../wasmflow/wasmflow-rpc" }
wasmflow-loader = { path = "../../wasmflow/wasmflow-loader" }
wasmflow-collection-wasm = { path = "../../wasmflow/wasmflow-collection-wasm" }
wasmflow-collection-cli = { path = "../../wasmflow/wasmflow-collection-cli" }
wasmflow-runtime = { path = "../../wasmflow/wasmflow-runtime" }
wasmflow-host = { path = "../../wasmflow/wasmflow-host" }
wasmflow-manifest = { path = "../../wasmflow/wasmflow-manifest" }
wasmflow-test = { path = "../../wasmflow/wasmflow-test" }
wasmflow-wascap = { path = "../../wasmflow/wasmflow-wascap" }
wasmflow-oci = { path = "../../wasmflow/wasmflow-oci" }
wasmflow-grpctar = { path = "../../wasmflow/wasmflow-grpctar" }
logger = { path = "../../wasmflow/logger" }
seeded-random = { path = "../../misc/seeded-random" }
tap = { path = "../../misc/tap" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true, features = ["derive"] }
nkeys = "0.2"
atty = "0.2"
jaq-core = "0.9"
markup-converter = "0.2"
oci-distribution = { version = "0.9", features = [
  "rustls-tls",
], default-features = false }
async-recursion = { workspace = true }
git2 = { version = "0.16", features = [
  "ssh",
  "https",
  "vendored-openssl",
], default-features = false }

[dev-dependencies]
test_bin = "0.4"
trycmd = "0.14"

[[bin]]
name = "wasmflow"
path = "src/main.rs"
