[package]
name = "wasmflow"
version = "0.3.1"
edition = "2021"
default-run = "wasmflow"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmflow-invocation = { path = "../../sdk/wasmflow-invocation" }
wasmflow-packet = { path = "../../sdk/wasmflow-packet" }
wasmflow-codec = { path = "../../sdk/wasmflow-codec" }
wasmflow-entity = { path = "../../sdk/wasmflow-entity" }
wasmflow-interface = { path = "../../sdk/wasmflow-interface" }
wasmflow-rpc = { path = "../../wasmflow/wasmflow-rpc" }
seeded-random = { path = "../../misc/seeded-random" }
wasmflow-loader = { path = "../../wasmflow/wasmflow-loader" }
wasmflow-collection-wasm = { path = "../../wasmflow/wasmflow-collection-wasm" }
wasmflow-collection-cli = { path = "../../wasmflow/wasmflow-collection-cli" }
wasmflow-runtime = { path = "../../wasmflow/wasmflow-runtime" }
wasmflow-transport = { path = "../../sdk/wasmflow-transport", features = [
  "all",
] }
wasmflow-host = { path = "../../wasmflow/wasmflow-host" }
wasmflow-manifest = { path = "../../wasmflow/wasmflow-manifest" }
wasmflow-test = { path = "../../wasmflow/wasmflow-test" }
cli-common = { path = "../cli-common" }
logger = { path = "../../wasmflow/logger" }
tap = { path = "../../misc/tap" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
clap = { version = "3.0", features = ["derive"] }
nkeys = "0.2"
serde_json = "1.0"
serde = "1.0"
atty = "0.2"
anyhow = "1.0"

[dev-dependencies]
test_bin = "0.3"
trycmd = "0.13"

[[bin]]
name = "wasmflow"
path = "src/main.rs"
