[package]
name = "wasmflow"
version = "0.4.0"
edition = "2021"
default-run = "wasmflow"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-common = { path = "../cli-common" }
wasmflow-sdk = { path = "../../wasmflow/wasmflow-sdk", features = ["v1"] }
wasmflow-rpc = { path = "../../wasmflow/wasmflow-rpc" }
wasmflow-loader = { path = "../../wasmflow/wasmflow-loader" }
wasmflow-collection-wasm = { path = "../../wasmflow/wasmflow-collection-wasm" }
wasmflow-collection-cli = { path = "../../wasmflow/wasmflow-collection-cli" }
wasmflow-runtime = { path = "../../wasmflow/wasmflow-runtime" }
wasmflow-host = { path = "../../wasmflow/wasmflow-host" }
wasmflow-manifest = { path = "../../wasmflow/wasmflow-manifest" }
wasmflow-test = { path = "../../wasmflow/wasmflow-test" }
logger = { path = "../../wasmflow/logger" }
seeded-random = { path = "../../misc/seeded-random" }

tap = { path = "../../misc/tap" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
clap = { version = "3.0", features = ["derive"] }
nkeys = "0.2"
serde_json = "1.0"
serde = "1.0"
atty = "0.2"
anyhow = "1.0"

[dev-dependencies]
test_bin = "0.3"
trycmd = "0.13"

[[bin]]
name = "wasmflow"
path = "src/main.rs"
