[package]
name = "tokio-test-bin"
version = "0.3.0"
authors = [
  "Michael Mc Donnell <michael@mcdonnell.dk>",
  "Jarrod Overson <jsoverson@gmail.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/test_bin"
homepage = "https://github.com/MichaelMcDonnell/test_bin"
repository = "https://github.com/MichaelMcDonnell/test_bin"
readme = "README.md"
description = """
A crate for getting the crate binary in an integration test.
"""

[dependencies]
tokio = { workspace = true, features = ["process", "io-util"] }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = [
  "macros",
  "process",
  "net",
  "rt-multi-thread",
] }
test-log = "0.2"
tracing = { workspace = true }
env_logger = { workspace = true }

[[bin]]
name = "test_bin"
path = "src/test_bin.rs"
