[package]
name = "wick-stdlib"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "The default standard library for the Wick project."

[features]

[dependencies]
wick-packet = { workspace = true }
flow-component = { workspace = true, features = ["invocation"] }
wick-rpc = { workspace = true }
wick-interface-types = { workspace = true, features = ["parser"] }
seeded-random = { workspace = true, features = ["uuid"] }
tracing = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
futures = { workspace = true }

[dev-dependencies]
wick-logger = { workspace = true }
test-logger = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
