[package]
name = "wasmflow-collection-link"
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
description = "SDK for native and WASM Wasmflow components"
documentation = "https://wasmflow.com"
keywords = ["wasm", "wasmflow", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasmflow-component = { path = "../wasmflow-component", version = "0.10.0-beta.4" }

[dependencies]
wasmflow-packet = { path = "../wasmflow-packet", version = "0.10.0-beta.4" }
wasmflow-output = { path = "../wasmflow-output", version = "0.10.0-beta.4" }
wasmflow-entity = { path = "../wasmflow-entity", version = "0.10.0-beta.4" }
wasmflow-codec = { path = "../wasmflow-codec", version = "0.10.0-beta.4" }
serde = { workspace = true, features = ["derive"] }
tokio-stream = { workspace = true, features = [] }

[dev-dependencies]
env_logger = { workspace = true }
test-log = "0.2.8"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
anyhow = { workspace = true }
wasmflow-packet = { path = "../wasmflow-packet", features = [] }
