[package]
name = "vino-wascap"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wascap = { path = "../../../forks/wascap" }
serde = { version = "1.0", features = ["derive"] }
vino-types = { path = "../../../sdk/crates/vino-types" }
thiserror = "1.0"
parity-wasm = "0.42.1"
data-encoding = "2.3.2"
ring = "0.16"
nuid = "0.3"
tracing = "0.1"

[dev-dependencies]
criterion = { version = "0.3", features = [] }
