[package]
name = "wick-component-wasm"
version = "0.3.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Implementation and loader for Wick WASM components."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
# Wick
wick-config = { workspace = true, features = ["config"] }
wick-packet = { workspace = true }
flow-component = { workspace = true, features = ["invocation"] }
wick-interface-types = { workspace = true }
wick-wasm-engine = { workspace = true }

# Wasmtime
wasmtime = { workspace = true, features = ["component-model", "async"] }
wasmtime-wasi = { workspace = true, features = ["tokio"] }

tokio = { workspace = true, features = ["sync"] }

# Misc
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
structured-output = { workspace = true }
parking_lot = { workspace = true }
derive_builder = { workspace = true }
