[package]
name = "wick-component-wasm"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Implementation and loader for Wick WASM components."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
wasmrs = { workspace = true }
wasmrs-rx = { workspace = true }
wasmrs-host = { workspace = true }
wasmrs-wasmtime = { workspace = true }
wasmrs-codec = { workspace = true }
wick-packet = { workspace = true }
wick-interface-types = { workspace = true }
wick-rpc = { workspace = true }
wick-wascap = { workspace = true }
wick-config = { workspace = true }
flow-component = { workspace = true }
seeded-random = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
wick-logger = { workspace = true }
test-logger = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
