[package]
name = "asset-container"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Manage local and remote assets in your structs "
version = "0.3.0"
include = ["src/**/*", "README.md", "!**/assets/**/*"]

[dependencies]
thiserror = { workspace = true }
futures = { workspace = true }
bitflags = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
wick-logger = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }
tokio-util = { workspace = true, features = ["io", "codec"] }
tokio-stream = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
