[package]
name = "wick-invocation-server"
version = "0.2.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Generic implementation of a wick RPC server."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-rpc = { workspace = true }
flow-component = { workspace = true, features = ["invocation"] }
tonic = { workspace = true, features = ["tls"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["net"] }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
wick-packet = { workspace = true }

[dev-dependencies]
wick-logger = { workspace = true }
test-logger = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
