[package]
name = "wick-invocation-server"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-rpc = { workspace = true }
tonic = { workspace = true, features = ["tls"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["net"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
wick-packet = { workspace = true }

[dev-dependencies]
logger = { workspace = true }
test-logger = { workspace = true }
anyhow = { workspace = true }
test-native-component = { workspace = true }
futures = { workspace = true }
