[package]
name = "wick-invocation-server"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-rpc = { path = "../wick-rpc" }
tonic = { workspace = true, features = ["tls"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["net"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
derivative = "2.2"
parking_lot = { workspace = true }
wick-packet = { path = "../wick-packet", features = [] }

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
anyhow = { workspace = true }
test-native-collection = { path = "../../integration/test-native-collection" }
futures = { workspace = true }
