[package]
name = "test-component"
version = "0.0.1"
description = ""
authors = [""]
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["host", "guest"]
host = []
guest = []

[dependencies]
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
wasmflow-sdk = { path = "../../wasmflow/wasmflow-sdk", features = ["v1"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
env_logger = { version = "0.10" }
test-log = "0.2"
