[package]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
name = "wasmflow-manifest"
version = "0.1.0"
publish = false

[dependencies]
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
wasmflow-parser = { path = "../wasmflow-parser" }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
shellexpand = { workspace = true }
serde-value = { workspace = true }
num-traits = "0.2"
serde-with-expand-env = "1.1"

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = "1"
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
