[package]
name = "wick-runtime"
version = "0.23.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "The runtime for the Wick project."
include = ["src/**/*", "LICENSE", "README.md"]

[features]

[dependencies]
#
# Core wick deps
#
flow-graph = { workspace = true }
flow-graph-interpreter = { workspace = true }
flow-component = { workspace = true }
wick-packet = { workspace = true, features = ["validation", "rng", "std"] }
wick-interface-types = { workspace = true, features = ["value"] }
wick-config = { workspace = true, features = ["config"] }
wick-component-wasm = { workspace = true }
wick-stdlib = { workspace = true }
wick-rpc = { workspace = true }
wick-interface-http = { workspace = true }
#
# High level components
#
wick-sql = { workspace = true }
wick-http-client = { workspace = true }
#
# Wasmtime
#
wasmtime = { workspace = true }
#
# For Time trigger
#
cron = { workspace = true }
#
# For HTTP Trigger
#
hyper = { workspace = true, features = ["runtime", "server"] }
hyper-staticfile = { workspace = true }
hyper-reverse-proxy = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }
openapiv3 = { workspace = true }
#
# For CLI Trigger
#
atty = { workspace = true }
#
# The rest
#
seeded-random = { workspace = true }
structured-output = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true, features = [
  "time",
  "sync",
  "signal",
  "rt-multi-thread",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
derive_builder = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
wick-invocation-server = { workspace = true }
wick-logger = { workspace = true }
test-logger = { workspace = true }
pretty_assertions = { workspace = true }
lazy_static = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true, features = ["time", "rt-multi-thread", "macros"] }
reqwest = { workspace = true }
wasmrs-codec = { workspace = true }
rstest = { workspace = true }
wick-packet = { workspace = true, features = ["test"] }
