[package]
name = "wick-runtime"
version = "0.22.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "The runtime for the Wick project."

[features]

[dependencies]
cron = { workspace = true }
chrono = { workspace = true }
wick-packet = { workspace = true, features = ["validation"] }
flow-graph = { workspace = true }
flow-graph-interpreter = { workspace = true }
flow-component = { workspace = true }
wick-interface-types = { workspace = true, features = ["value"] }
wick-config = { workspace = true }
wick-component-wasm = { workspace = true }
wick-stdlib = { workspace = true }
wick-rpc = { workspace = true }
wick-interface-http = { workspace = true }
seeded-random = { workspace = true }
structured-output = { workspace = true }
# High level components
wick-sqlx = { workspace = true }
wick-http-client = { workspace = true }
wick-azure-sql = { workspace = true }
# The rest
tokio = { workspace = true, features = [
  "macros",
  "time",
  "sync",
  "signal",
  "rt-multi-thread",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
atty = { workspace = true }
hyper = { workspace = true, features = ["runtime", "server"] }
url = { workspace = true }
bytes = { workspace = true }
hyper-staticfile = { workspace = true }
hyper-reverse-proxy = { workspace = true }
derive_builder = { workspace = true }

[dev-dependencies]
wick-invocation-server = { workspace = true }
wick-logger = { workspace = true }
test-logger = { workspace = true }
pretty_assertions = { workspace = true }
lazy_static = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true, features = ["time", "rt-multi-thread", "macros"] }
reqwest = { workspace = true }
wasmrs-codec = { workspace = true }
rstest = { workspace = true }
