[package]
name = "wick-runtime"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
publish = false

[features]

[dependencies]
wick-packet = { path = "../wick-packet", features = [] }
flow-graph = { path = "../flow-graph" }
flow-graph-interpreter = { path = "../flow-graph-interpreter" }
wick-interface-types = { path = "../wick-interface-types" }
wick-config-component = { path = "../wick-config-component" }
wick-loader-utils = { path = "../wick-loader-utils" }
wick-component-wasm = { path = "../wick-component-wasm" }
wick-stdlib = { path = "../wick-stdlib" }
wick-rpc = { path = "../wick-rpc" }
seeded-random = { path = "../../misc/seeded-random" }
tokio = { workspace = true, features = [
  "macros",
  "time",
  "sync",
  "rt-multi-thread",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
serde-value = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
atty = "0.2"

[dev-dependencies]
wick-invocation-server = { path = "../wick-invocation-server" }
test-native-collection = { path = "../../integration/test-native-collection" }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
pretty_assertions = "1"
lazy_static = "1.4"
anyhow = { workspace = true }
runtime-testutils = { path = "./tests/runtime_utils" }
futures = { workspace = true }
