[package]
name = "wick-host"
version = "0.5.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "A batteries-included implementation of the Wick runtime."
include = ["src/**/*", "LICENSE", "README.md"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
seeded-random = { workspace = true }
flow-component = { workspace = true }
wick-runtime = { workspace = true }
wick-packet = { workspace = true }
wick-interface-types = { workspace = true }
wick-config = { workspace = true, features = ["config"] }
wick-component-cli = { workspace = true, features = ["grpc"] }
wick-rpc = { workspace = true }
wick-invocation-server = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
http = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
derive_builder = { workspace = true }
option-utils = { workspace = true }
async-trait = { workspace = true }
structured-output = { workspace = true }


[dev-dependencies]
wick-logger = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "time",
  "io-std",
  "io-util",
  "macros",
] }
anyhow = { workspace = true }
tokio-stream = { workspace = true }
wick-packet = { workspace = true, features = ["test"] }
