[package]
name = "wick-host"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
seeded-random = { workspace = true }
wick-runtime = { workspace = true }
wick-packet = { workspace = true }
wick-interface-types = { workspace = true }
wick-config = { workspace = true }
wick-component-cli = { workspace = true }
wick-rpc = { workspace = true }
wick-invocation-server = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
http = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
logger = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "time",
  "io-std",
  "io-util",
  "macros",
] }
anyhow = { workspace = true }
tokio-stream = { workspace = true }
