[package]
name = "wick-test-logger"
version = "0.2.0"
edition = "2021"
authors = [
  "Daniel Mueller <deso@posteo.net>",
  "Jarrod Overson <jsoverson@gmail.com>",
]
include = ["src/lib.rs", "LICENSE-*", "README.md"]
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Logging-enabled test harness for the wick logging library"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = [
  "full",
  "derive",
  "proc-macro",
  "clone-impls",
  "printing",
  "parsing",
] }
proc-macro-crate = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wick-logger = { workspace = true }
