[package]
name = "baseline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
strip = "symbols"
codegen-units = 1
debug = false
lto = true
opt-level = "z"
panic = "abort"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmrs-guest = { version = "0.8", features = ["logging"] }
wick-component = { path = "../../wick/wick-component" }
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"

[build-dependencies]
wick-component-codegen = { path = "../../wick/wick-component-codegen" }
