[package]
name = "wasmflow-grpctar"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
serde_json = "1"
serde_yaml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tar = "0.4.38"
wasmflow-interface = { path = "../wasmflow-interface" }
wasmflow-wascap = { path = "../wasmflow-wascap" }

[dev-dependencies]
anyhow = { workspace = true }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
clap = { workspace = true, features = ["derive", "env"] }
async-recursion = { workspace = true }
env_logger = { workspace = true }
