---
name: 'test-component'
kind: wick/component@v1
metadata:
  version: '1'
component:
  kind: wick/component/wasmrs@v1
  ref: ../../../../integration/test-baseline-component/build/baseline.signed.wasm
  operations:
    - name: add
      inputs:
        - name: left
          type: u64
        - name: right
          type: u64
      outputs:
        - name: output
          type: u64
    - name: error
      inputs:
        - name: input
          type: string
      outputs:
        - name: output
          type: string
    - name: validate
      inputs:
        - name: input
          type: string
      outputs:
        - name: output
          type: string
