[package]
name = "tap"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
testanything = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
