[package]
name = "wasmflow-packet"
version = "0.10.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/wasmflow/wasmflow-sdk"
description = "Rust library encapsulating the message packets sent across Wasmflow components."
documentation = "https://wasmflow.com"
keywords = ["wasmflow", "actor", "flow"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
homepage = "https://wasmflow.com"

[features]
default = []
all = ["v0"]
v0 = []

[dependencies]
wasmflow-codec = { path = "../wasmflow-codec", version = "0.10.0-beta.4" }
serde = { workspace = true, features = ["derive"] }
serde-value = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
test-log = "0.2"
anyhow = { workspace = true }
tracing = { workspace = true }
