[package]
name = "cli-common"
version = "0.4.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]


[dependencies]
clap = { version = "3.0", features = ["derive", "env"] }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
tokio-stream = "0.1.8"
serde_json = { version = "1.0" }
tracing = "0.1"

[dev-dependencies]
anyhow = "1.0"
