[package]
name = "cli-common"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]


[dependencies]
wasmflow-sdk = { path = "../../wasmflow/wasmflow-sdk", features = ["v1"] }

tokio-stream = "0.1.8"
serde_json = { version = "1.0" }
tracing = "0.1"
anyhow = "1.0"

[dev-dependencies]
