version: 0
id: test
initializers:
  mydb:
    uses: nanobus.migrate.postgres/v1
    with:
      dataSource: "postgres://postgres:postgres@localhost:5432/blog?sslmode=disable"
      directory: migrations/
interfaces:
  test:
    testexec:
      steps:
        - uses: "@postgres/exec"
          with:
            resource: mydb
            data: '{"userID":"TestID","title":"Test Title","body":"Test Body"}'
            sql: |-
              INSERT INTO blog (user_id, title, body, time)
              VALUES ($1, $2, $3, now())
              RETURNING *
            args:
              - input.userId
              - input.title
              - input.body
