[package]
name = "wasmflow-keyvalue-redis"
version = "0.0.0"
edition = "2021"
license-file = "LICENSE"

[features]
default = ["host"]
host = []

[dependencies]
wasmflow-collection-cli = { path = "../../wasmflow/wasmflow-collection-cli" }
wasmflow-rpc = { path = "../../wasmflow/wasmflow-rpc" }
# wasmflow-interface-keyvalue = { path = "../../interfaces/wasmflow-interface-keyvalue", features = [
#   "host",
#   "guest",
# ] }
redis = { version = "0.22", features = ["tokio-comp"] }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync", "rt-multi-thread"] }
once_cell = { workspace = true }
tokio-util = { version = "0.7", features = ["codec"] }
clap = { workspace = true, features = ["derive", "env"] }
tracing = { workspace = true }

[dev-dependencies]
logger = { path = "../../wasmflow/logger" }
serde_json = { workspace = true }
tonic = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
test-logger = { path = "../../misc/test-logger" }
