[package]
name = "wasmflow-transport"
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
description = "Transport layer for Wasmflow packets"
documentation = "https://wasmflow.com"
keywords = ["serde", "wasmflow", "packet", "transport"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
all = ["async"]
async = ["tokio", "tokio-stream", "parking_lot"]

[dependencies]
wasmflow-packet = { path = "../wasmflow-packet", version = "0.10.0-beta.4", features = [
  "v0",
] }
wasmflow-codec = { path = "../wasmflow-codec", version = "0.10.0-beta.4" }
wasmflow-macros = { path = "../wasmflow-macros", version = "0.10.0-beta.4" }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
# raw
serde-value = { workspace = true }
# json
serde_json = { workspace = true }
# async
tokio = { workspace = true, features = [], optional = true }
tokio-stream = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }

[dev-dependencies]
test-log = "0.2.8"
anyhow = "1.0"
env_logger = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
