[package]
name = "wasmflow-loader"
version = "0.0.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tracing = { workspace = true }
thiserror = { workspace = true }
wasmflow-oci = { path = "../../wasmflow/wasmflow-oci" }
tokio = { workspace = true, features = ["fs"] }
