[package]
name = "wick-rpc"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
client = ["tokio/fs"]

[dependencies]
wick-packet = { workspace = true, features = ["invocation"] }
wasmrs-rx = { workspace = true, features = [] }
wick-interface-types = { workspace = true }
tonic = { workspace = true, features = ["tls"] }
prost = { workspace = true }
prost-types = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["net"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async-stream = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
dyn-clone = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true, default-features = false, features = [
  "prost",
] }

[dev-dependencies]
