[package]
name = "wick-rpc"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Library for implementing or interacting with a wick runtime via gRPC"
include = ["src/**/*", "LICENSE", "README.md"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
client = ["tokio/fs"]

[dependencies]
wick-packet = { workspace = true, features = ["invocation"] }
wick-interface-types = { workspace = true }
tonic = { workspace = true, features = [
  "tls",
  "transport",
  "codegen",
  "prost",
] }
prost = { workspace = true, features = ["prost-derive"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["net"] }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
option-utils = { workspace = true }

[dev-dependencies]
