[package]
name = "wick-interface-types"
version = "0.14.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Types used by Wick components"
documentation = "https://candle.dev"
keywords = ["types", "wick", "wasmflow"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
homepage = "https://candle.dev"

[features]
default = ["yaml", "parser"]
parser = ["nom"]
yaml = ["serde_yaml"]
typeid = ["serde_json"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
nom = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }
test-log = { workspace = true }
env_logger = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
