[package]
name = "performance-mark"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/candlecorp/wick"
license = "Apache-2.0"
description = "A utility library for marking events and durations for performance-tracking purposes."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
derive_serde = ["serde/derive"]

[dependencies]
serde = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
