---
apiVersion: wick.candle.dev/v1alpha1
kind: Enum
metadata:
  name: HttpVersion
fields:
  - name: HTTP10
    value: "HTTP/1.0"
  - name: HTTP11
    value: "HTTP/1.1"
  - name: HTTP20
    value: "HTTP/2.0"
