[package]
name = "wasmflow-collection-grpctar"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
wasmflow-grpctar = { path = "../wasmflow-grpctar" }
wasmflow-loader = { path = "../wasmflow-loader" }
wasmflow-rpc = { path = "../wasmflow-rpc", features = ["client"] }
wasmflow-collection-cli = { path = "../wasmflow-collection-cli", default-features = false }
parking_lot = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tar = "0.4"
tokio = { workspace = true, features = ["process"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shellexpand = "2.1"

[dev-dependencies]
test-native-collection = { path = "../../integration/test-native-collection" }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
tokio = { workspace = true, features = ["macros"] }
tokio-stream = { workspace = true }
anyhow = { workspace = true }
wasmflow-wascap = { path = "../wasmflow-wascap" }
workspace-root = { path = "../../misc/workspace-root" }
