[package]
name = "wasmflow-collection-grpctar"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
wasmflow-grpctar = { path = "../wasmflow-grpctar" }
wasmflow-loader = { path = "../wasmflow-loader" }
wasmflow-rpc = { path = "../wasmflow-rpc", features = ["client"] }
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
wasmflow-collection-cli = { path = "../wasmflow-collection-cli", default-features = false }
parking_lot = "0.12"
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1"
tar = "0.4"
tokio = { version = "1", features = ["process"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
shellexpand = "2.1"

[dev-dependencies]
test-native-collection = { path = "../../integration/test-native-collection" }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
tokio = { version = "1", features = ["macros"] }
tokio-stream = "0.1.7"
anyhow = "1.0"
wasmflow-wascap = { path = "../wasmflow-wascap" }
workspace-root = { path = "../../misc/workspace-root" }
