[package]
name = "wick"
version = "0.4.1"
edition = "2021"
default-run = "wick"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-packet = { path = "../../wick/wick-packet" }
wick-interface-types = { path = "../../wick/wick-interface-types", features = [
] }
wick-rpc = { path = "../../wick/wick-rpc", features = ["client"] }
wick-loader-utils = { path = "../../wick/wick-loader-utils" }
wick-component-wasm = { path = "../../wick/wick-component-wasm" }
wick-component-cli = { path = "../../wick/wick-component-cli" }
wick-runtime = { path = "../../wick/wick-runtime" }
wick-host = { path = "../../wick/wick-host" }
wick-config = { path = "../../wick/wick-config" }
wick-test = { path = "../../wick/wick-test" }
wick-wascap = { path = "../../wick/wick-wascap" }
wick-oci-utils = { path = "../../wick/wick-oci-utils" }
wick-grpctar = { path = "../../wick/wick-grpctar" }
logger = { path = "../../wick/logger" }
seeded-random = { path = "../../misc/seeded-random" }
tap = { path = "../../misc/tap" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true, features = ["derive"] }
nkeys = "0.2"
atty = "0.2"
jaq-core = "0.9"
markup-converter = "0.2"
oci-distribution = { version = "0.9", features = [
  "rustls-tls",
], default-features = false }
async-recursion = { workspace = true }
# git2 = { version = "0.16", features = [
#   "ssh",
#   "https",
#   "vendored-openssl",
# ], default-features = false }

[dev-dependencies]
test_bin = "0.4"
trycmd = "0.14"
logger = { path = "../../wick/logger" }
test-logger = { path = "../../misc/test-logger" }
tokio-test-bin = { path = "../../misc/tokio-test-bin" }
regex = { workspace = true }

[[bin]]
name = "wick"
path = "src/main.rs"
