[package]
name = "wick-postgres"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"

[features]

[dependencies]
wick-packet = { workspace = true }
wick-config = { workspace = true }
wick-rpc = { workspace = true }
wick-interface-types = { workspace = true, features = ["parser"] }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["process"] }
futures = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }
tokio-postgres = { workspace = true, features = ["with-serde_json-1"] }
postgres-openssl = { workspace = true }
openssl = { workspace = true, features = ["vendored"] }
byteorder = { workspace = true, features = [] }
bytes = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
logger = { workspace = true }
test-logger = { workspace = true }
anyhow = { workspace = true }
