---
format: 0
network:
  collections:
    - namespace: wapc
      kind: WaPC
      reference: nothing.wasm
  schematics:
    - name: missing_collection
      uses:
        validate:
          id: wapc::validate
      connections:
        - <> => validate[input]
        - validate[output] => <>
