[package]
name = "wick-interface-http"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "HTTP interface types for the wick framework and components"
repository = "https://github.com/candlecorp/wick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["host"]
host = []
guest = []

[dev-dependencies]

[dependencies]
wasmrs-guest = { workspace = true }
wick-component = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bytes = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
wick-component-codegen = { workspace = true }
