[package]
name = "wick-interface-http"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "HTTP interface types for the wick framework and components"
repository = "https://github.com/candlecorp/wick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dev-dependencies]

[dependencies]
wick-component = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
wick-component-codegen = { workspace = true }
