[package]
name = "vino-interpreter"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

thiserror = "1.0"
tracing = "0.1"
tracing-futures = "0.2"
vino-schematic-graph = { path = "../vino-schematic-graph" }
vino-types = { path = "../../../sdk/crates/vino-types" }
vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-transport = { path = "../../../sdk/crates/vino-transport" }
performance-mark = { path = "../../misc/performance-mark" }
rxrust = "0.15.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1"
futures = "0.3"
uuid = { version = "0.8", features = ["v4"] }
parking_lot = "0.12"
crossbeam = "0.8"
once_cell = "1.10"

[dev-dependencies]
vino-manifest = { path = "../vino-manifest" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
anyhow = "1.0"
serde_json = "1.0"
