[package]
name = "wick-test"
version = "0.2.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Test runner for Wick components"
include = ["src/**/*", "LICENSE", "!**/*_test.*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Wick
flow-component = { workspace = true, features = ["invocation"] }
wick-packet = { workspace = true }
wick-config = { workspace = true, features = ["config"] }
wick-interface-types = { workspace = true }
# TAP interface
tap-harness = { workspace = true }
# WasmRS
wasmrs-codec = { workspace = true }
# Common dependencies
json_dotpath = { workspace = true }
either = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }
assert-json-diff = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
wick-logger = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
anyhow = { workspace = true }
rstest = { workspace = true }
