[package]
name = "wick-test"
version = "0.0.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Test runner for Wick components"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Wick
flow-component = { workspace = true }
wick-packet = { workspace = true }
wick-config = { workspace = true }
wick-rpc = { workspace = true }
# TAP interface
tap-harness = { workspace = true }
# WasmRS
wasmrs-codec = { workspace = true }
# Common dependencies
serde = { workspace = true, features = ["derive"] }
serde-value = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
wick-logger = { workspace = true }
test-logger = { workspace = true }
test-native-component = { workspace = true }
anyhow = { workspace = true }
