[package]
name = "seeded-random"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = { workspace = true }
rand_chacha = "0.3"
parking_lot = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
