[package]
name = "seeded-random"
version = "0.5.0"
edition = "2021"
license = "Apache-2.0"
description = "A utility library for deterministic randomness."
repository = "https://github.com/candlecorp/wick"

[features]
default = ["rng"]
rng = ["rand/rand_chacha", "rand/small_rng"]
std = ["rand/std", "rand/std_rng"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = { workspace = true, default-features = false, features = [] }
rand_chacha = { workspace = true, default-features = false }
parking_lot = { workspace = true }
uuid = { workspace = true, default-features = false, optional = true }
