[package]
name = "wasmflow-schematic-graph"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
serde_json = "1.0"
wasmflow-manifest = { path = "../wasmflow-manifest" }
tokio = { version = "1", features = ["macros", "rt"] }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
anyhow = "1.0"
pretty_assertions = "1.1"
