[package]
name = "tap-harness"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "A Test-Anything-Protocol library"
include = ["src/lib.rs", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
testanything = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
