version: 0
network:
  schematics:
    - name: senders
      instances:
        SENDER:
          id: core::sender
          data:
            output: "1234512345"
      connections:
        - SENDER[output] => <>
