[package]
name = "wasmflow-collection-nats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
wasmflow-rpc = { path = "../wasmflow-rpc" }
wasmflow-mesh = { path = "../wasmflow-mesh" }
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
parking_lot = "0.12"
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"

[dev-dependencies]
test-native-collection = { path = "../../integration/test-native-collection" }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
tokio = { version = "1", features = ["macros"] }
tokio-stream = "0.1.7"
anyhow = "1.0"
