[package]
name = "wick-package"
version = "0.2.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Utility for managing and fetching packages for the wick project."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-config = { workspace = true }
wick-oci-utils = { workspace = true }
asset-container = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["fs"] }
sha256 = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
test-logger = { workspace = true }
wick-logger = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
async-recursion = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
walkdir = "2.3"
