[package]
name = "wasmflow-interpreter"
version = "0.0.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
wasmflow-schematic-graph = { path = "../wasmflow-schematic-graph" }
wasmflow-manifest = { path = "../wasmflow-manifest" }
wasmflow-parser = { path = "../wasmflow-parser" }
seeded-random = { path = "../../misc/seeded-random" }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-futures = { workspace = true }
performance-mark = { path = "../../misc/performance-mark" }
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "macros"] }
tokio-stream = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
parking_lot = { workspace = true }
serde_json = { workspace = true }
serde-value = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
anyhow = { workspace = true }
serde_json = { workspace = true }
