[package]
name = "wasmflow-interpreter"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
wasmflow-schematic-graph = { path = "../wasmflow-schematic-graph" }
wasmflow-manifest = { path = "../wasmflow-manifest" }
seeded-random = { path = "../../misc/seeded-random" }

thiserror = "1.0"
tracing = "0.1"
tracing-futures = "0.2"
performance-mark = { path = "../../misc/performance-mark" }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
tokio-stream = "0.1"
futures = "0.3"
uuid = { version = "1.1", features = ["v4"] }
parking_lot = "0.12"
serde_json = "1.0"
serde-value = "0.7"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
async-recursion = "1.0"


[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
anyhow = "1.0"
serde_json = "1.0"
