[package]
name = "flow-component"
version = "0.6.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Create components to execute in Wick runtimes"
include = ["src/**/*", "LICENSE"]
readme = "README.md"

[features]
default = []
invocation = ["wick-packet/invocation"]
uuid = ["seeded-random/uuid"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-packet = { workspace = true, features = ["datetime"] }
wick-interface-types = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
seeded-random = { workspace = true, features = ["rng"] }

[dev-dependencies]
