[package]
name = "flow-component"
version = "0.5.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Create components to execute in Wick runtimes"

[features]
default = []
traits = ["wick-packet/invocation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-packet = { workspace = true }
wick-interface-types = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
