[package]
name = "wick-logger"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Wick's logging library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-xdg = { workspace = true }
tracing = { workspace = true }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true, features = [
  "env-filter",
  "fmt",
  "json",
  "time",
] }
tracing-bunyan-formatter = "0.3"
tracing-appender = "0.2"
time = { version = "0.3", features = ["formatting"] }
ansi_term = "0.12"
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt"] }
thiserror = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true, features = ["rt-tokio"] }
opentelemetry-jaeger = { workspace = true, features = [
  "rt-tokio",
  "hyper_collector_client",
  "collector_client"
] }
