[package]
name = "wick-logger"
version = "0.2.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Wick's logging library"

[features]
console = ["console-subscriber"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-xdg = { workspace = true }
tracing = { workspace = true }
console-subscriber = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = [
  "env-filter",
  "fmt",
  "time",
  "parking_lot",
  "ansi",
] }
tracing-appender = { workspace = true }
time = { workspace = true, features = ["formatting"] }
ansi_term = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = [
  "tokio",
  "grpc-tonic",
  "trace",
] }
