[package]
name = "wick-component-codegen"
version = "0.4.0"
edition = "2021"
description = "Code generator for wick components"
repository = "https://github.com/candlecorp/wick"
license = "Apache-2.0"
include = ["src/**/*", "LICENSE"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-config = { workspace = true, features = ["config", "v1"] }
wick-interface-types = { workspace = true }
anyhow = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["parsing"] }
proc-macro2 = { workspace = true }
heck = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "fs"] }
derive_builder = { workspace = true }
serde_json = { workspace = true }
bitflags = { workspace = true }
itertools = { workspace = true }
check_keyword = { workspace = true }
prettyplease = { workspace = true }

[dev-dependencies]
wick-logger = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
