[package]
name = "wick-component-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde_yaml = { workspace = true }
wick-config = { workspace = true }
wick-interface-types = { workspace = true }
anyhow = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
heck = { workspace = true }

[dev-dependencies]
logger = { workspace = true }
test-logger = { workspace = true }
