[package]
name = "wick-operation"
version = "0.2.0"
edition = "2021"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
include = ["src/lib.rs", "README.md"]
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Proc macro for generating operation implementations"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true, features = ["proc-macro"] }
quote = { workspace = true, features = ["proc-macro"] }
syn = { workspace = true, features = [
  "full",
  "derive",
  "proc-macro",
  "clone-impls",
  "printing",
  "parsing",
] }
proc-macro-crate = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wick-logger = { workspace = true }
