[package]
name = "wick-component-cli"
version = "0.1.1"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Simple implementation of a wick CLI interface for Rust components."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ['cli']
reflection = ["tonic-reflection"]
cli = ['grpc', 'mesh']
grpc = ['wick-rpc', 'tonic/tls', 'wick-invocation-server', 'wick-config']
mesh = ['wick-rpc', 'wick-config']

[dependencies]
flow-component = { workspace = true, features = ["invocation"] }
wick-rpc = { workspace = true, optional = true }
wick-config = { workspace = true, optional = true, features = ["config"] }
wick-interface-types = { workspace = true }
wick-packet = { workspace = true, features = ["datetime"] }
wick-invocation-server = { workspace = true, optional = true }
cfg-if = { workspace = true }
tonic = { workspace = true, optional = true }
tonic-reflection = { workspace = true, default-features = false, optional = true }
tokio = { workspace = true, features = [
  "macros",
  "fs",
  "net",
  "signal",
  "rt-multi-thread",
] }
tokio-stream = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "std"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
wick-logger = { workspace = true }
test-logger = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true, features = ["json"], default-features = false }
anyhow = { workspace = true }
serde_json = { workspace = true }
