[package]
name = "wafl"
version = "0.5.0"
edition = "2021"
default-run = "wafl"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-common = { path = "../cli-common" }
wasmflow-sdk = { path = "../../wasmflow/wasmflow-sdk", features = ["v1"] }
wasmflow-grpctar = { path = "../../wasmflow/wasmflow-grpctar" }
wasmflow-collection-cli = { path = "../../wasmflow/wasmflow-collection-cli" }
wasmflow-rpc = { path = "../../wasmflow/wasmflow-rpc", features = ["client"] }
wasmflow-wascap = { path = "../../wasmflow/wasmflow-wascap" }
logger = { path = "../../wasmflow/logger" }

git2 = { version = "0.14", features = [
  "ssh",
  "https",
  "vendored-openssl",
], default-features = false }

async-recursion = "1.0"
nkeys = "0.2"
tracing = "0.1"
clap = { version = "3.0", features = ["derive", "env"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

atty = "0.2"
oci-distribution = { version = "0.9", features = [
  "rustls-tls",
], default-features = false }
wasmflow-oci = { path = "../../wasmflow/wasmflow-oci" }
anyhow = "1.0"

[dev-dependencies]
trycmd = "0.13"

[[bin]]
name = "wafl"
path = "src/main.rs"
