version: 0
network:
  triggers:
    reference: &comp ../../integration/test-main-network-component/build/test_main_network_component_s.wasm
    data:
      wasi:
        preopened_dirs:
          - "$TEST_TEMPDIR"
        map_dirs:
          - ["/", "$TEST_TEMPDIR"]
  collections:
    - namespace: main
      kind: WaPC
      reference: *comp
  schematics:
    - name: inner-schematic
      instances:
        COMPONENT: main::byte-count
      connections:
        - <>[input] => COMPONENT[input]
        - COMPONENT[output] => <>[output]
