version: 0
network:
  schematics:
    - name: first_schematic
      instances:
        add:
          id: wafl::math::add
      connections:
        - from:
            instance: <input>
            port: left
          to:
            instance: add
            port: left
        - from:
            instance: <input>
            port: right
          to:
            instance: add
            port: right
        - from:
            instance: add
            port: output
          to:
            instance: <output>
            port: output
    - name: second_schematic
      instances:
        log:
          id: wafl::core::log
      connections:
        - from:
            instance: <input>
            port: input
          to:
            instance: log
            port: input
        - from:
            instance: log
            port: output
          to:
            instance: <output>
            port: output
