[package]
name = "wick-trigger-wasm-component"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Implementation and loader for Wick WASM components."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
# Wick
wick-runtime = { workspace = true }
wick-config = { workspace = true }
wick-packet = { workspace = true }
wick-trigger = { workspace = true }

# Wasmtime
wasmtime = { workspace = true, features = ["component-model", "async"] }
wasmtime-wasi = { workspace = true, features = ["tokio"] }

tokio = { workspace = true, features = ["sync"] }

# Misc
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
structured-output = { workspace = true }
parking_lot = { workspace = true }
