[package]
name = "wasmflow-mesh"
version = "0.0.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
nats = { version = "0.15" }
tracing = "0.1"
wasmflow-rpc = { path = "../wasmflow-rpc" }
thiserror = "1.0"
nkeys = "0.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["time", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
futures = "0.3"
parking_lot = "0.12"
once_cell = "1.5"

[dev-dependencies]
test-native-collection = { path = "../../integration/test-native-collection" }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
anyhow = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
pretty_assertions = "1.2"
