[package]
name = "wasmflow-mesh"
version = "0.0.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
nats = { version = "0.15" }
tracing = { workspace = true }
wasmflow-rpc = { path = "../wasmflow-rpc" }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["time", "rt-multi-thread"] }
tokio-stream = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
test-native-collection = { path = "../../integration/test-native-collection" }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
pretty_assertions = "1.2"
