[package]
name = "wasmflow-boundary"
version = "0.10.0-beta.4"
edition = "2021"
license = "BSD-3-Clause"
description = "SDK for native and WASM Wasmflow components"
documentation = "https://wasmflow.com"
keywords = ["wasm", "wasmflow", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[badges]
maintenance = { status = "actively-developed" }

[features]
v1 = []

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasmflow-codec = { path = "../wasmflow-codec", version = "0.10.0-beta.4" }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmflow-invocation = { path = "../wasmflow-invocation", version = "0.10.0-beta.4" }
wasmflow-packet = { path = "../wasmflow-packet", version = "0.10.0-beta.4" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
