[package]
name = "wasmflow-collection-wasm"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

# wasm3 = ["wasm3-provider"]
[dependencies]
wasmrs = { workspace = true }
wasmrs-rx = { workspace = true }
wasmrs-host = { workspace = true }
wasmrs-wasmtime = { workspace = true }
wasmrs-codec = { workspace = true }
wasmflow-packet-stream = { path = "../wasmflow-packet-stream" }
wasmflow-entity = { path = "../wasmflow-entity" }
wasmflow-interface = { path = "../wasmflow-interface" }
wasmflow-rpc = { path = "../wasmflow-rpc" }
wasmflow-wascap = { path = "../wasmflow-wascap" }
wasmflow-loader = { path = "../wasmflow-loader" }
wasmflow-manifest = { path = "../wasmflow-manifest" }
seeded-random = { path = "../../misc/seeded-random" }
tokio = { workspace = true, features = ["fs"] }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde-value = { workspace = true }
tokio-stream = { workspace = true }
async-stream = "0.3.2"
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
futures = { workspace = true }
anyhow = { workspace = true }
