[package]
name = "wasmflow-collection-wasm"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wasmtime"]
wasmtime = ["wasmtime-provider"]
# wasm3 = ["wasm3-provider"]

[dependencies]
wasmflow-rpc = { path = "../wasmflow-rpc" }
wasmflow-wascap = { path = "../wasmflow-wascap" }
wasmflow-loader = { path = "../wasmflow-loader" }
wasmflow-sdk = { path = "../wasmflow-sdk", features = ["v1"] }
wasmflow-manifest = { path = "../wasmflow-manifest" }
seeded-random = { path = "../../misc/seeded-random" }

tokio = { version = "1", features = ["fs"] }
parking_lot = "0.12"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-value = "0.7"

# wasmtime-provider = { version = "1.0", optional = true, features = ["cache"] }
# wapc = "1.0"
# wapc-pool = "1.0"
wasmtime-provider = { git = "https://github.com/wasmflow/wapc-rs", branch = "master", optional = true, features = [
  "cache",
] }
wapc = { git = "https://github.com/wasmflow/wapc-rs", branch = "master" }
wapc-pool = { git = "https://github.com/wasmflow/wapc-rs", branch = "master" }


tokio-stream = "0.1.7"
async-stream = "0.3.2"
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1.50"

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
futures = "0.3"
anyhow = "1.0"
