[package]
name = "wasmflow-collection-grpc"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
wasmflow-rpc = { path = "../wasmflow-rpc", features = ["client"] }
parking_lot = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["process"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
http = "0.2"

[dev-dependencies]
wasmflow-invocation-server = { path = "../../wasmflow/wasmflow-invocation-server" }
test-native-collection = { path = "../../integration/test-native-collection" }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
tokio = { workspace = true, features = ["macros"] }
tokio-stream = { workspace = true }
anyhow = { workspace = true }
