format: 0
network:
  triggers:
    reference: &comp ../../integration/test-main-network-component/build/test_main_network_component.signed.wasm
    data:
      wasi:
        dirs:
          '/': '$TEST_TEMPDIR'
  collections:
    - namespace: main
      kind: WaPC
      reference: *comp
  schematics:
    - name: inner-schematic
      uses:
        COMPONENT: main::byte-count
      connections:
        - <>[input] => COMPONENT[input]
        - COMPONENT[output] => <>[output]
