---
format: 0
network:
  collections:
    - namespace: wasi
      kind: WaPC
      reference: ../../integration/test-wasi-component/build/test_wasi_component.signed.wasm
      data:
        wasi:
          dirs:
            '/': '$TEST_TEMPDIR'
  schematics:
    - name: wasi_component
      collections:
        - wasi
      uses:
        read:
          id: wasi::fs-read
      connections:
        - <> => read[filename]
        - read[contents] => <>
