[package]
name = "wasmflow-parser"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
publish = false

[dependencies]
lazy_static = "1.4"
regex = "1"
serde = { version = "1" }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
pretty_assertions = "1"
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
