[package]
name = "wick-oci-utils"
version = "0.4.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "OCI utility library for the Wick project"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-xdg = { workspace = true }
oci-distribution = { workspace = true, features = [
  "rustls-tls",
], default-features = false }
thiserror = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["fs"] }
sha256 = { workspace = true }
bytes = { workspace = true }
regex = { workspace = true }
once_cell = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true, features = ["rust_backend"] }
derive_builder = { workspace = true }
getset = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
test-logger = { workspace = true }
wick-logger = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
async-recursion = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
rstest = { workspace = true }
