baseURL = 'https://candle.dev/docs/'
languageCode = 'en-us'
title = 'Candle Documentation'
theme = 'hugo-theme-techdoc'

[params]
menu_style = "open-menu"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true
xhtml = true
