[package]
name = "vino-host"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]


[dependencies]
vino-random = { path = "../vino-random" }
vino-runtime = { path = "../vino-runtime" }
vino-lattice = { path = "../vino-lattice" }
vino-manifest = { path = "../vino-manifest" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-provider-cli = { path = "../vino-provider-cli" }
vino-codec = { path = "../../../sdk/crates/vino-codec" }
vino-rpc = { path = "../vino-rpc" }
vino-invocation-server = { path = "../vino-invocation-server" }
vino-entity = { path = "../../../sdk/crates/vino-entity" }
vino-macros = { path = "../../../sdk/crates/vino-macros" }
tracing = "0.1"

thiserror = "1.0"
nkeys = { path = "../../../forks/nkeys" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1.50"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
http = "0.2"
once_cell = "1.8"
parking_lot = "0.11"
uuid = "0.8"

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
tokio = { version = "1", features = [
  "net",
  "rt-multi-thread",
  "time",
  "io-std",
  "io-util",
  "macros",
] }
anyhow = "1.0"
tokio-stream = "0.1.7"
