[package]
name = "test-native-collection"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["host", "guest"]
host = []
guest = []

[dependencies]
wick-packet = { path = "../../wick/wick-packet", features = [
] }
wick-interface-types = { path = "../../wick/wick-interface-types", features=["parser"] }
wick-rpc = { workspace = true }
serde = { version = "1", features = ["derive"] }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }
anyhow = {workspace = true}
futures = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
logger = { path = "../../wick/logger" }
clap = { version = "3.0", features = ["derive", "env"] }
tracing = { workspace = true }
anyhow = "1.0"
pretty_assertions = "1.2"
