[package]
name = "wick-trigger-cli"
version = "0.1.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Implementation and loader for Wick WASM components."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
wick-trigger = { workspace = true }
wick-runtime = { workspace = true }
wick-config = { workspace = true }
wick-packet = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

tokio = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
structured-output = { workspace = true }
parking_lot = { workspace = true }

#
# Specific for CLI Trigger
#
wick-interface-cli = { workspace = true }
atty = { workspace = true }

[dev-dependencies]

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
wick-logger = { workspace = true }
test-logger = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
pretty_assertions = { workspace = true }
wick-config = { workspace = true, features = ["v1"] }
