[package]
name = "vow"
version = "0.4.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-common = { path = "../cli-common" }
tap = { path = "../../misc/tap" }
vino-test = { path = "../../vino/vino-test" }
vino-rpc = { path = "../../vino/vino-rpc" }
vino-wascap = { path = "../../vino/vino-wascap" }
vino-provider-cli = { path = "../../vino/vino-provider-cli" }
vino-provider-wasm = { path = "../../vino/vino-provider-wasm" }
vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-codec = { path = "../../../sdk/crates/vino-codec" }
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }

clap = { version = "3.0", features = ["derive", "env"] }
serde_json = "1.0"
serde-value = "0.7.0"
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
thiserror = "1.0"
atty = "0.2"
once_cell = "1.8"

[dev-dependencies]
logger = { path = "../../vino/logger" }
anyhow = "1.0"
trycmd = "0.13"

[[bin]]
name = "vow"
path = "src/main.rs"
