---
format: 0
network:
  collections:
    - namespace: wapc
      kind: WaPC
      reference: ../../integration/test-baseline-component/build/baseline.signed.wasm
      data:
        default_err: 'custom error'
  schematics:
    - name: test
      instances:
        validate:
          id: wapc::validate
      connections:
        - <> => validate[input]
        - validate[output] => <>
