[package]
name = "wasmflow-entity"
version = "0.10.0-beta.2"
edition = "2021"
license = "BSD-3-Clause"
description = "Entities found in a Wasmflow network"
documentation = "https://wasmflow.com"
keywords = ["wasmflow", "flow"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
wasmflow-macros = { path = "../wasmflow-macros", version = "0.10.0-beta.2" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
url = "2.2"

[dev-dependencies]
