[package]
name = "wasmflow-test"
version = "0.0.0"
edition = "2021"
license = "Elastic-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tap = { path = "../../misc/tap" }
wasmflow-packet-stream = { path = "../wasmflow-packet-stream", features = [] }
wasmrs-codec = { path = "../../../../wasmrs-rust/crates/wasmrs-codec", features = [
] }
wasmflow-entity = { path = "../wasmflow-entity"}
wasmflow-rpc = { path = "../wasmflow-rpc" }
serde = { workspace = true, features = ["derive"] }
serde-value = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }
