[package]
name = "wick-asset-reference"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Data structures for representing Wick assets and asset references."
version = "0.3.0"

[dependencies]
wick-oci-utils = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
asset-container = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true }
parking_lot = { workspace = true }
normpath = { workspace = true }
getset = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
wick-logger = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
asset-container = { workspace = true }
rstest = { workspace = true }
