name: Lint Commits

on:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Number of commits
        id: step_one
        run: |
          echo "NUM_COMMITS=$((${{ github.event.pull_request.commits }} + 1))" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.NUM_COMMITS }}

      - uses: actions/setup-node@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('.github/workflows/commitlint.yaml') }}
          restore-keys: npm-

      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Git log
        run: |
          git log -n ${{ github.event.pull_request.commits }} | cat

      - name: Validate commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --config ./etc/commitlint.config.js --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}  --verbose
