name: Build and Push Docs Site

on:
  push:
    branches:
      - main
    paths:
      - "docsite/**"

jobs:
  build-and-push-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # use nodejs action
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      # run npm build on /docs directory
      - name: Build
        run: |
          cd docsite
          npm install
          npm run build
      - name: Package and push
        uses: nanobus/push-action@v1
        with:
          path: "docsite/bus.yaml"
          username: ${{ secrets.CANDLE_REG_USERNAME }}
          password: ${{ secrets.CANDLE_REG_PASSWORD }}
