name: Build Docs site

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rust toolchain cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-rust-nightly-docs

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustc, cargo, rust-docs

      - uses: extractions/setup-just@v1

      - name: Build rustdocs
        run: just rustdoc

      - name: Build site
        working-directory: ./docs
        run: hugo --minify

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

      - name: Publish Wick Package
        uses: candlecorp/wick-push-action@v0.0.3
        id: push
        with:
          path: 'docs/docs.wick'
          username: ${{ secrets.CANDLE_REG_USERNAME }}
          password: ${{ secrets.CANDLE_REG_PASSWORD }}
          tags: latest ${{ steps.prep.outputs.BUILD_ID }}
