[package]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
name = "wick-config"
description = "Wick manifest configuration format."
version = "0.24.0"

[dependencies]
flow-expression-parser = { workspace = true }
wick-packet = { workspace = true, default-features = false }
wick-interface-types = { workspace = true, features = ["yaml"] }
wick-oci-utils = { workspace = true }
wick-asset-reference = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
shellexpand = { workspace = true }
serde-value = { workspace = true }
num-traits = { workspace = true }
serde-with-expand-env = { workspace = true }
assets = { workspace = true }
derive-assets = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
url = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
logger = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
assets = { workspace = true }
tokio-stream = { workspace = true }
