[package]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
name = "wick-config"
version = "0.1.0"
publish = false

[dependencies]
flow-expression-parser = { path = "../flow-expression-parser" }
wick-packet = { path = "../wick-packet" }
wick-interface-types = { path = "../wick-interface-types", features = ["yaml"] }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
shellexpand = { workspace = true }
serde-value = { workspace = true }
num-traits = "0.2"
serde-with-expand-env = "1.1"

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = "1"
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
