[package]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
name = "wick-config"
version = "0.21.0"
publish = false

[dependencies]
flow-expression-parser = { workspace = true }
wick-packet = { workspace = true, default-features = false }
wick-interface-types = { workspace = true, features = ["yaml"] }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
shellexpand = { workspace = true }
serde-value = { workspace = true }
num-traits = { workspace = true }
serde-with-expand-env = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
logger = { workspace = true }
test-logger = { workspace = true }
