[package]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
name = "wick-config"
description = "Wick manifest configuration format."
version = "0.27.0"
include = ["src/**/*", "README.md"]
readme = "README.md"

[features]
default = ["v1", "v0", "config"]
config = [
  "wick-asset-reference",
  "flow-component",
  "flow-expression-parser/std",
  "wick-packet",
  "liquid-json",
  "url",
  "derive-asset-container",
  "asset-container",
  "tracing",
  "derive_builder",
  "glob",
  "parking_lot",
  "option-utils",
  "property",
  "normpath",
  "async-recursion",
  "wildmatch",
  "once_cell",
]
v1 = [
  "liquid-json",
  "num-traits",
  "serde-value",
  "serde_with",
  "flow-expression-parser",
]
v0 = [
  "liquid-json",
  "num-traits",
  "serde-value",
  "serde-with-expand-env",
  "flow-expression-parser",
]

[dependencies]

flow-expression-parser = { workspace = true, default-features = false, optional = true }
wick-interface-types = { workspace = true, features = [
  "yaml",
  "parser",
  "value",
] }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

regex = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }

# config + v1 + v0
liquid-json = { workspace = true, features = ["serde"], optional = true }

# config
flow-component = { workspace = true, optional = true }
wick-packet = { workspace = true, default-features = false, features = [
  "validation",
  "std",
  "rng",
], optional = true }
url = { workspace = true, features = ["serde"], optional = true }
wick-asset-reference = { workspace = true, optional = true }
derive-asset-container = { workspace = true, optional = true }
asset-container = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
derive_builder = { workspace = true, optional = true }
glob = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }
option-utils = { workspace = true, optional = true }
property = { workspace = true, optional = true }
normpath = { workspace = true, optional = true }
async-recursion = { workspace = true, optional = true }
wildmatch = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }

# v1 & v0
num-traits = { workspace = true, optional = true }

# v1
serde_with = { workspace = true, features = ["std", "macros"], optional = true }

# v0
serde-value = { workspace = true, optional = true }
serde-with-expand-env = { workspace = true, optional = true }


[dev-dependencies]
wick-xdg = { workspace = true }
wick-oci-utils = { workspace = true }
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
wick-logger = { workspace = true }
test-logger = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-test = { workspace = true }
asset-container = { workspace = true }
tokio-stream = { workspace = true }
rstest = { workspace = true }
